mongodbdata:
    image: mongo:2.6
    volumes:
        - /data/db
    restart: "no"
    command: /bin/echo "Data-only container for mongodb."

mongodb:
    image: mongo:2.6
    volumes_from:
        - mongodbdata
    expose:
        - "27017"
    command: --smallfiles

orion:
    image: fiware/orion
    links:
        - mongodb
    expose:
        - "1026"
    command: -dbhost mongodb
    
iotacpp:
    image: telefonicaiot/iotacpp
    links:
        - mongodb
        - orion
    expose:
        - "8080"
        - "8081"
        - "1883"    
            
